server:
  port: 9091
  http2:
    enabled: true


spring:
  application:
    name: learn-graphql-java
  data:
    mongodb:
      port: 27017
      database: ecommerce-ql
      auto-index-creation: true

graphql:
  tools:
    schema-location-pattern:**/*.graphqls
